const fs = require('fs');
let code = fs.readFileSync('src/pages/ShoppingCartCheckout.jsx', 'utf8');
const replacements = [
  ['// ?디???품 박스 배송 ?보', '// 에디톤 제품 박스 배송 정보'],
  ["'?디???톤'", "'에디톤 스톤'"],
  ["'?디???퀘어'", "'에디톤 스퀘어'"],
  ["'?디???드'", "'에디톤 우드'"],
  ['4??/ 1박스', '4장 / 1박스'],
  ['7??/ 1박스', '7장 / 1박스'],
  ['// 최소 배송??기본 3?후 (?바구니 ?? ??고 부족이??고 ?정???는 경우, 가????? ?짜 ?용)', '// 최소 배송일 기본 3일 후 (장바구니 상품 중 재고 부족이거나 입고 예정일이 있는 경우, 가장 늦은 날짜 적용)'],
  ['// ?량???재 ?고보다 많? 경우 (?절 ?는 ?량 부? ?고?정??체크', '// 주문 수량이 현재 재고보다 많은 경우 (품절 또는 수량 부족) 입고예정일 체크'],
  ['// ?장? 매번 ?? ???으므?주소???동?로 불러?? ?음', '// 현장은 매번 다를 수 있으므로 주소는 자동으로 불러오지 않음'],
  ["alert('주문 ?역 ?인 ??의???의?주?요.');", "alert('주문 내역 확인 및 약관에 동의해주세요.');"],
  ["alert('배송 ?보?모두 ?력?주?요.');", "alert('배송 정보를 모두 입력해주세요.');"],
  ["alert('결제가 ?료?었?니?? 주문 ?인 ?이지??동?니??');", "alert('결제가 완료되었습니다. 주문 확인 페이지로 이동합니다.');"],
  ["alert('결제가 ?료?었?니?? 비회??주문 조회 ?이지??동?니??');", "alert('결제가 완료되었습니다. 비회원 주문 조회 페이지로 이동합니다.');"],
  ['{/* ?편번호 검??모달 */}', '{/* 우편번호 검색 모달 */}'],
  ['주소 검??                            </h3>', '주소 검색                            </h3>'],
  ['<Link className="text-slate-500 hover:text-primary" to="/">??/Link>', '<Link className="text-slate-500 hover:text-primary" to="/">홈</Link>'],
  ['<span className="text-slate-900 dark:text-slate-100 font-medium">?바구니</span>', '<span className="text-slate-900 dark:text-slate-100 font-medium">장바구니</span>'],
  ['<h1 className="text-2xl sm:text-3xl font-black mb-6 sm:mb-8 tracking-tight">?바구니 ??전 결제</h1>', '<h1 className="text-2xl sm:text-3xl font-black mb-6 sm:mb-8 tracking-tight">장바구니 및 안전 결제</h1>'],
  ['{/* ?스?탑: ?이??이?웃 */}', '{/* 데스크탑: 테이블 레이아웃 */}'],
  ['<th className="px-4 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">?품?보</th>', '<th className="px-4 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">상품정보</th>'],
  ['<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">?션</th>', '<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">옵션</th>'],
  ['<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 text-center">?량</th>', '<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 text-center">수량</th>'],
  ['<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 text-right">금액</th>', '<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 text-right">금액</th>'],
  ['<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 text-center whitespace-nowrap">??</th>', '<th className="px-3 py-4 text-xs font-bold uppercase tracking-wider text-slate-500 text-center whitespace-nowrap">삭제</th>'],
  ['?바구니???긴 ?품???습?다.', '장바구니에 담긴 상품이 없습니다.'],
  [".includes('???')", ".includes('타일')"],
  [".includes('?디??')", ".includes('에디톤')"],
  [".includes('?코??')", ".includes('에코노')"],
  [".includes('?레?티지')", ".includes('프레스티지')"],
  [".includes('??')", ".includes('장')"],
  [".includes('?트')", ".includes('시트')"],
  [".includes('?리미엄')", ".includes('프리미엄')"],
  [".includes('?탠?드')", ".includes('스탠다드')"],
  [".includes('?스컴포??')", ".includes('엑스컴포트')"],
  [".includes('?판')", ".includes('합판')"],
  ["!packagingText.includes('?')", "!packagingText.includes('장')"],
  ["`${packagingText} / 1?`", "`${packagingText} / 1장`"],
  ["iconEmoji = isTileOrBox ? '?' : '?';", "iconEmoji = isTileOrBox ? '📦' : '📏';"],
  ["'박스배송'", "'박스배송'"],
  ["'롤배??'", "'롤배송'"],
  ['{item.option}', '{item.option}'],
  ['.toLocaleString()}??', '.toLocaleString()}원'],
  ['{/* 모바??카드 ?이?웃 */}', '{/* 모바일 카드 레이아웃 */}'],
  ['{/* ?품 ??지 */}', '{/* 상품 이미지 */}'],
  ['{/* ?품 ?보 */}', '{/* 상품 정보 */}'],
  ['기본 ?션', '기본 옵션'],
  ['?션: {item.option}', '옵션: {item.option}'],
  ['{/* 배송 ?보 뱃? */}', '{/* 배송 정보 뱃지 */}'],
  ['{/* ?량 & 금액 */}', '{/* 수량 & 금액 */}'],
  ['<h3 className="text-lg font-bold mb-4">배송 ?보 ?력</h3>', '<h3 className="text-lg font-bold mb-4">배송 정보 입력</h3>'],
  ['<label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">?름</label>', '<label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">이름</label>'],
  ['placeholder="?름???력?주?요"', 'placeholder="이름을 입력해주세요"'],
  ['<label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">?락?</label>', '<label className="block text-sm font-medium text-slate-700 dark:text-slate-300 mb-1">연락처</label>'],
  ['주소 검?을 ?용?주?요', '주소 검색을 이용해주세요'],
  ['주소 검?? ', '주소 검색'],
  ['주소 검??                                    </button>', '주소 검색                                    </button>'],
  ['?세 주소??력?주?요 (?? ?수 ?력)', '상세 주소를 입력해주세요 (동/호/층수 입력)'],
  ['?장 관리인 ?락?', '현장 관리인 연락처'],
  ['(?택)', '(선택)'],
  ['(?장 관리자 번호)', '(현장 관리자 번호)'],
  ['하차 조건 <span className="text-slate-400 font-normal ml-1">(?택)</span>', '하차 조건 <span className="text-slate-400 font-normal ml-1">(선택)</span>'],
  ['?차 조건', '하차 조건'],
  ['?? 지게차 ?차, 까??기? ?의?항 ?력', '지게차 하차, 까대기 등 주의사항 입력'],
  ['배송 ?망??', '배송 희망일'],
  ['?절 ?품(?는 ?고 부????고 ?정??${minDeliveryDate}) ?후로만 ?택 가?합?다.', '품절 또는 재고 부족 상품의 입고 예정일(${minDeliveryDate}) 이후로만 선택 가능합니다.'],
  ['배송 주문 최소 3?후', '배송 주문 최소 3일 후'],
  ['?력?신 ?보???활??배송 ?주문 ?인???해?만 ?용?니??', '입력하신 정보는 원활한 배송 및 주문 확인을 위해서만 이용됩니다.'],
  ['결제 ?단 ?택', '결제 수단 선택'],
  ['?용카드', '신용카드'],
  ['?시???? 결제', '일시불/할부 결제'],
  ['카카?페??', '카카오페이'],
  ['간편?고 빠른 결제', '간편하고 빠른 결제'],
  ['?시?계좌?체', '실시간 계좌이체'],
  ['?스?로 ?전결제 지??', '에스크로 안전결제 지원'],
  ['<h3 className="text-lg font-bold mb-4">?? ?의</h3>', '<h3 className="text-lg font-bold mb-4">약관 동의</h3>'],
  ['<h3 className="text-lg font-bold mb-4">?? ?의</h3>', '<h3 className="text-lg font-bold mb-4">약관 동의</h3>'],
  ['주문 ?역 ?인 ??의?항 ?의 (?수)', '주문 내역 확인 및 유의사항 동의 (필수)'],
  ['주문 ?역 ?인 ??의?항 ?의 (?수)', '주문 내역 확인 및 유의사항 동의 (필수)'],
  ['?품??주문 ?량, ?션, 결제 금액???인???며, ?핑??용?? ?개인?보 처리방침???의?니??', '상품의 주문 수량, 옵션, 결제 금액을 확인하였으며, 쇼핑몰 이용약관 및 개인정보 처리방침에 동의합니다.'],
  ['?히 바닥???단 ?품??경우 ?순 변??반품???한?????음???인???니??', '특히 바닥재 재단 상품의 경우 단순 변심에 의한 반품이 제한될 수 있음을 확인하였습니다.'],
  ['[?세??보기]', '[자세히 보기]'],
  ['결제 ?약', '결제 요약'],
  ['?품 금액', '상품 금액'],
  ['(?업??)', '(사업자용)'],
  ['부가??10%)', '부가세(10%)'],
  ['배송?', '배송비'],
  ['?업???인 ?택', '사업자 할인 혜택'],
  ['?{discountRate}% ?감', '약 {discountRate}% 절감'],
  ['?감', '절감'],
  ['?반가 ?계', '일반가 합계'],
  ['?업?? ?용', '사업자가 적용'],
  ['??감 금액', '총 절감 금액'],
  ['결제?기', '결제하기'],
  ['?? ?의 ?요', '약관 동의 필요'],
  ['?? ?의 ?요', '약관 동의 필요'],
  ['?핑 계속?기', '쇼핑 계속하기'],
  ['?전 결제 ?스??보증', '안전 결제 에스크로 보증'],
  ['고객?의 결제 ?보??보호?어 ?전?게 처리?며, 개인?보 처리방침???라 철???보호?니??', '고객님의 결제 정보는 철저히 보호되어 안전하게 처리되며, 개인정보 처리방침에 따라 관리됩니다.']
];

replacements.forEach(([a, b]) => {
  code = code.split(a).join(b);
});

// Since some of the replaced unicode strings might be different from expected, handle the raw ? chars with fallback
code = code.replace(/주문 \?역 \?인 \?\?의\?\?의\?주\?요\./g, '주문 내역 확인 및 약관에 동의해주세요.');
code = code.replace(/결제가 \?료\?었\?니\?\? 주문 \?인 \?이지\?\?동\?니\?\?/g, '결제가 완료되었습니다. 주문 확인 페이지로 이동합니다.');
code = code.replace(/결제가 \?료\?었\?니\?\? 비회\?\?주문 조회 \?이지\?\?동\?니\?\?/g, '결제가 완료되었습니다. 비회원 주문 조회 페이지로 이동합니다.');

fs.writeFileSync('src/pages/ShoppingCartCheckout.jsx', code);
console.log('Done');
